apiVersion: v1
kind: PersistentVolume
metadata:
  name: actia-db-pv
  namespace: actia-engineering
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/actia-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actia-db-pvc
  namespace: actia-engineering
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
